![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [1]:
import numpy as np

In [2]:
my_array = np.arange(0,10)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [3]:
print(my_array[8:6:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [8]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [9]:
matriz=np.arange(1,21)

In [10]:
matriz=matriz.reshape(4,5)

In [11]:
print(matriz)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [13]:
matriz = np.arange(1, 21).reshape(4, 5)
resultado = matriz[[0, 1], :2]

print(resultado)


[[1 2]
 [6 7]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [15]:
matriz = np.arange(1, 21).reshape(4, 5)
resultado = matriz[np.ix_([0, 2], [0, 2, 4])]

print(resultado)


[[ 1  3  5]
 [11 13 15]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [17]:
matriz = np.arange(1, 21).reshape(4, 5)
resultado = matriz[:3, ::-1]

print(resultado)


[[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [18]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

In [19]:
loros = x[x == "Loro"]

print(loros)


['Loro' 'Loro']


In [21]:
indices_parrot = np.where(x == "Loro")
parrot = x[indices_parrot]

print(parrot)

['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [22]:
ejercicio_9 = np.arange(1, 21)

array_matrices = ejercicio_9.reshape(2, 5, 2)

print(array_matrices)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]


## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [23]:
ejercicio_10 = matriz[::-1, ::-1]

print(ejercicio_10)


[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [25]:
ejercicio_11 = np.zeros(10)

tamaño_bytes = ejercicio_11.nbytes

print(f"Array de 10 ceros: {ejercicio_11}")
print(f"Tamaño en memoria: {tamaño_bytes} bytes")

ejercicio_11[3] = 1

print(f"ejercicio_11_modificado: {ejercicio_11}")

Array de 10 ceros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Tamaño en memoria: 80 bytes
ejercicio_11_modificado: [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]


## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [26]:
ejercicio_12 = np.arange(10, 50)

ejercicio_12_invertido = ejercicio_12[::-1]

print(ejercicio_12_invertido)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [27]:
ejercicio_13 = np.array([1, 2, 0, 0, 4, 0])

no_cero = np.nonzero(ejercicio_13)

indices = no_cero[0]

print(indices)

[0 1 4]


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [31]:
ejercicio_14 = np.random.rand(10, 10)

valor_minimo = np.min(ejercicio_14)
valor_maximo = np.max(ejercicio_14)

print("ejercicio 14 10x10:")
print(ejercicio_14)
print(f"\nValor mínimo: {valor_minimo}")
print(f"Valor máximo: {valor_maximo}")

ejercicio 14 10x10:
[[0.45487734 0.90705598 0.43994515 0.69293233 0.60065394 0.11431734
  0.10937725 0.03948584 0.36568597 0.05075538]
 [0.84838154 0.89815517 0.87268356 0.36314486 0.7266775  0.23107616
  0.16865223 0.9136542  0.85607856 0.64883183]
 [0.56808337 0.51246199 0.09410163 0.3123143  0.34940452 0.41510595
  0.90507665 0.85808546 0.87356736 0.04493145]
 [0.77326583 0.43120576 0.01240938 0.24483692 0.98339804 0.97633661
  0.23275853 0.69039758 0.54762528 0.59014678]
 [0.56979098 0.35162242 0.11135512 0.47227183 0.13179725 0.45003733
  0.02567065 0.99827587 0.7042549  0.28860869]
 [0.38419254 0.80116411 0.39105009 0.14595947 0.36675466 0.92509011
  0.6171406  0.94024981 0.78913775 0.76393924]
 [0.55449196 0.91850209 0.84373954 0.95551528 0.61642765 0.295112
  0.93033722 0.62019573 0.68847623 0.110651  ]
 [0.89902417 0.94839893 0.26054871 0.01602118 0.18050577 0.59351244
  0.5852664  0.23193803 0.25771185 0.29546919]
 [0.28325164 0.8314061  0.44225997 0.94166573 0.51290304 0.960

## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [32]:
ejercicio_15 = np.random.rand(30)

media_vector = np.mean(ejercicio_15)

print("ejercicio 15:")
print(ejercicio_15)
print(f"\nMedia del vector: {media_vector}")

ejercicio 15:
[0.99996007 0.40575216 0.26913427 0.37758551 0.59725929 0.46941695
 0.87378194 0.10687186 0.94300709 0.38043565 0.29704461 0.78069143
 0.23118144 0.75196324 0.62477758 0.44603139 0.04978454 0.92175337
 0.70483102 0.66000683 0.27188406 0.41796938 0.71018706 0.58722232
 0.28241407 0.95259034 0.7173787  0.77648981 0.54855392 0.27721967]

Media del vector: 0.5477726516229993


## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [34]:
n = 8
matriz = np.ones((n, n), dtype=int) 
matriz[1:-1, 1:-1] = 0 

print(matriz)


[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]


## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [37]:
ejercicio_17 = np.zeros((8, 8), dtype=int)
ejercicio_17[1::2, ::2] = 1 
ejercicio_17[::2, 1::2] = 1  

print(ejercicio_17)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [38]:
bloque = np.array([[0, 1],
                   [1, 0]])

matriz = np.tile(bloque, (4, 4))

print(matriz)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [40]:
ejercicio_19 = np.random.rand(5, 5)

media = np.mean(ejercicio_19)
desviacion = np.std(ejercicio_19)

matriz_normalizada = (ejercicio_19 - media) / desviacion

print("ejercicio 19:")
print(ejercicio_19)
print("\nejercicio 19 normalizado:")
print(matriz_normalizada)

ejercicio 19:
[[0.0612453  0.3413011  0.62538489 0.8190861  0.15943384]
 [0.27195342 0.7861502  0.56495492 0.49884972 0.85907474]
 [0.37222792 0.4687541  0.83074232 0.57650265 0.97554916]
 [0.90662114 0.28836114 0.14871305 0.91137098 0.7615394 ]
 [0.69568607 0.31471694 0.37104727 0.02131585 0.59732486]]

ejercicio 19 normalizado:
[[-1.67319749 -0.67166358  0.34427525  1.0369884  -1.3220562 ]
 [-0.91966434  0.9192032   0.12816592 -0.10823912  1.17999552]
 [-0.56106326 -0.21586689  1.07867328  0.16946285  1.59653066]
 [ 1.35003068 -0.86098715 -1.36039584  1.36701705  0.83119021]
 [ 0.59568592 -0.76673369 -0.56528549 -1.81599298  0.24392711]]


## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [41]:
ejercicio_20 = np.arange(0, 11)
print("ejercicio 20:")
print(ejercicio_20)


ejercicio 20:
[ 0  1  2  3  4  5  6  7  8  9 10]


In [43]:
ejercicio_20_sustituido = np.where((ejercicio_20 >= 3) & (ejercicio_20 <= 8), -1, ejercicio_20)
print("\nArray con valores entre 3 y 8 reemplazados por -1:")
print(ejercicio_20_sustituido)



Array con valores entre 3 y 8 reemplazados por -1:
[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]


In [44]:
ejercicio_20_negado = np.where((ejercicio_20 >= 3) & (ejercicio_20 <= 8), -ejercicio_20, ejercicio_20)
print("\nArray con valores entre 3 y 8 negados:")
print(ejercicio_20_negado)



Array con valores entre 3 y 8 negados:
[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


## Ejercicio 21
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.